name: Aggiornamento Volantini Notturno

# Quando deve partire?
on:
  schedule:
    - cron: '0 3 * * *' # Tutti i giorni alle 03:00 del mattino (ora UTC)
  workflow_dispatch: # Questo ti permette di avviarlo anche manualmente con un click per fare i test!

jobs:
  aggiorna-offerte:
    runs-on: ubuntu-latest

    steps:
      - name: Clona il magazzino
        uses: actions/checkout@v3

      - name: Prepara Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # La versione del motore server

      - name: Installa le librerie
        run: npm install

      - name: Avvia gli scraper di tutti i negozi
        run: |
          node scraper_lidl.js
          node scraper_conad.js
          node scraper_esselunga.js
          # Qui in futuro aggiungeremo: node scraper_conad.js, node scraper_esselunga.js, ecc.

      - name: Salva i nuovi file JSON su GitHub
        run: |
          git config --global user.name 'GitHub Action Bot'
          git config --global user.email 'action@github.com'
          git add *.json
          # Se ci sono modifiche, salva e carica, altrimenti non fare nulla
          git diff --quiet && git diff --staged --quiet || (git commit -m "Aggiornamento offerte automatico" && git push)
